# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5ca2ab6634f2ea7161204a77a64febe6dca53d31b372830edfb4a08595f471d0d081717c771d896bbdbced58aab933d245cc754ca1e0c8ef5ac6c057628f2db

test:
  secret_key_base: b4a5eb0bfceda4885c15891f01d61c184e74f28cb2f41d000755ce51e93c3d52aa8b4773537b5f01baddcccbb0cef5ba74056f0d9d83f39c2c2e1e0ec30fc7ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
