source "http://gems.github.com"
source "http://rubygems.org"

gemspec path: File.expand_path(File.dirname(__FILE__) + "/../")

gem 'home_page', path: '../../../../home_page/home_page'

gem 'devise', github: 'plataformatec/devise'